### ISSUE TITLE
菜单超一屏后没有滚动条

### ISSUE THREAD

**Issue by leeyesong** [willin/gitbook-plugin-atoc#9]
求解决方案

**Comment by leeyesong** [comment]
补充下: 问题是把放在一级标题之前，菜单在侧边浮动时产生的

**Comment by willin** [comment]
手动根据需要添加样式，如：

```css
.atoc {
    max-height: 80vh;
    overflow-y: auto;
}
```
